# Essential NumPy Functions for Machine Learning

Hey there, fellow learner! 🎉 Welcome to this super exciting journey into NumPy – the ultimate tool for anyone diving into data science and machine learning. Whether you're just starting out or leveling up your skills, these NumPy functions are going to become your best friends!

Let's learn together, have some fun with code, and unlock the power of these functions to tackle real-world problems! 💪 Ready to roll up your sleeves and dive in? Let’s make learning NumPy a blast! 🚀



## Import NumPy module

Run the following code cell to import the NumPy module:

In [1]:
import numpy as np 

## Populate arrays with specific numbers

Call `np.array` to create a NumPy array with your own hand-picked values. For example, the following call to `np.array` creates an 8-element array:

In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


You can also use np.array to create a two-dimensional array. To create a two-dimensional array specify an extra layer of square brackets. For example, the following call creates a 3x2 array:

In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


To populate an array with all zeroes, call `np.zeros`. To populate an array with all ones, call `np.ones`.

## Populate arrays with sequences of numbers

You can populate an array with a sequence of numbers:

In [4]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


# 1. Array Creation and Manipulation


**np.array()**
- Converts a Python list (or other iterable) into a NumPy array.-

In [5]:
np.array([1, 2, 3])


array([1, 2, 3])

**np.zeros()**
 - Creates an array of zeros with the specified shape

In [6]:
np.zeros((3, 2))  # 3x2 array of zeros


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

**np.ones()**
- Creates an array of ones with the specified shape.

In [7]:
np.ones((2, 3))  # 2x3 array of ones


array([[1., 1., 1.],
       [1., 1., 1.]])

**np.arange()**
- Returns evenly spaced values within a given range.

In [8]:
np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]


array([0, 2, 4, 6, 8])

**np.linspace()**
- Creates an array of evenly spaced values over a specified range, useful for generating features or plotting points.

In [9]:
np.linspace(0, 1, 5)  # [0.   0.25 0.5  0.75 1.]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**np.reshape()**
- Reshapes an array without changing its data.

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.reshape(2, 3)  # Reshapes to 2x3 array


array([[1, 2, 3],
       [4, 5, 6]])

**np.ravel()**
- Flattens a multi-dimensional array into a 1D array.

In [11]:
np.ravel([[1, 2], [3, 4]])  # [1, 2, 3, 4]


array([1, 2, 3, 4])

# 2. Array Arithmetic & Mathematical Operations

**np.add()**
- Element-wise addition of arrays.

In [12]:
np.add([1, 2], [3, 4])  # [4, 6]


array([4, 6])

**np.subtract()**
- Element-wise subtraction of arrays.

In [13]:
np.subtract([5, 6], [1, 2])  # [4, 4]


array([4, 4])

**np.multiply()**
- Element-wise multiplication of arrays.

In [14]:
np.multiply([1, 2], [3, 4])  # [3, 8]


array([3, 8])

**np.divide()**
- Element-wise division of arrays.

In [15]:
np.divide([6, 8], [2, 4])  # [3.0, 2.0]


array([3., 2.])

**np.dot()**
- Dot product of two arrays. Used for matrix multiplication.

In [16]:
np.dot([1, 2], [3, 4])  # 11 (1*3 + 2*4)


11

**np.sum()**
- Sum of all elements in an array (or along a specified axis).

In [17]:
np.sum([1, 2, 3, 4])  # 10
np.sum([[1, 2], [3, 4]], axis=0)  # [4, 6]


array([4, 6])

**np.mean()**
- Computes the mean (average) of an array.

In [18]:
np.mean([1, 2, 3, 4])  # 2.5

2.5

**np.median()**
- Computes the median of an array.

In [19]:
np.median([1, 2, 3, 4])  # 2.5

2.5

**np.std()**
- Computes the standard deviation of an array.

In [20]:
np.std([1, 2, 3, 4])  # 1.118

1.118033988749895

**np.var()**
- Computes the variance of an array.

In [21]:
np.var([1, 2, 3, 4])  # 1.25

1.25

**np.max() / np.min()**
- Returns the maximum (or minimum) value of an array.

In [22]:
print(np.max([1, 5, 3]))  # 5
print(np.min([1, 5, 3]))  # 1

5
1


**np.exp()**
- Computes the exponential (e^x) of each element in an array.

In [23]:
np.exp([1, 2, 3])  # [2.718, 7.389, 20.086]

array([ 2.71828183,  7.3890561 , 20.08553692])

**np.log()**
- Computes the natural logarithm (ln(x)) of each element in an array.

In [24]:
np.log([1, np.e, np.e**2])  # [0, 1, 2]

array([0., 1., 2.])

**np.sqrt()**
- Computes the square root of each element in an array.

In [25]:
np.sqrt([1, 4, 9])  # [1., 2., 3.]

array([1., 2., 3.])

# 3. Linear Algebra

**np.linalg.inv()**
- Computes the inverse of a square matrix.

In [26]:
np.linalg.inv(np.array([[1, 2], [3, 4]]))  

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

**np.linalg.det()**
- Computes the determinant of a matrix.

In [27]:
np.linalg.det(np.array([[1, 2], [3, 4]]))  # -2.0

-2.0000000000000004

**np.linalg.eig()**
- Computes the eigenvalues and eigenvectors of a square matrix.

In [28]:
w, v = np.linalg.eig(np.array([[1, 2], [3, 4]]))  # w = eigenvalues, v = eigenvectors

**np.linalg.solve()**
- Solves a system of linear equations, Ax=b.

In [29]:
A = np.array([[3, 2], [1, 2]])
b = np.array([5, 5])
np.linalg.solve(A, b)  # Solution to Ax = b

array([0. , 2.5])

# 4. Random Number Generation

**np.random.rand()**
- Generates random numbers uniformly distributed between 0 and 1.

In [30]:
np.random.rand(3, 2)  # 3x2 array of random numbers

array([[0.22499575, 0.86852719],
       [0.54813529, 0.02595953],
       [0.94601796, 0.63258875]])

**np.random.randn()**
- Generates random numbers from a standard normal distribution (mean 0, variance 1).

In [31]:
np.random.randn(2, 2)  # 2x2 array of random numbers

array([[-1.59787218,  0.33489595],
       [-1.14248443, -0.71736064]])

**np.random.randint()**
- Generates random integers between specified limits.

In [32]:
np.random.randint(1, 10, size=3)  # Random integers between 1 and 10

array([7, 9, 4])

**np.random.shuffle()**
- Shuffles the elements of an array in place.

In [33]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr) # Array elements are shuffled randomly
arr

array([4, 5, 2, 1, 3])

# 5. Statistics and Distribution

**np.percentile()**
- Computes the percentile of an array.

In [34]:
np.percentile([1, 2, 3, 4, 5], 50)  # 3 (50th percentile)

3.0

**np.corrcoef()**
- Computes the Pearson correlation coefficient between two or more arrays.

In [35]:
np.corrcoef([1, 2, 3], [4, 5, 6])  # Correlation coefficient

array([[1., 1.],
       [1., 1.]])

**np.histogram()**
- Computes the histogram of an array.

In [36]:
np.histogram([1, 2, 2, 3, 3, 3, 4, 5], bins=5)

(array([1, 2, 3, 1, 1], dtype=int64), array([1. , 1.8, 2.6, 3.4, 4.2, 5. ]))

# 6. Other Useful Functions

**np.concatenate()**
- Concatenates two or more arrays along a specified axis.

In [37]:
np.concatenate([np.array([1, 2]), np.array([3, 4])])  # [1, 2, 3, 4]

array([1, 2, 3, 4])

**np.split()**
- Splits an array into multiple sub-arrays.


In [38]:
np.split(np.array([1, 2, 3, 4, 5, 6]), 3)  # [array([1, 2]), array([3, 4]), array([5, 6])]

[array([1, 2]), array([3, 4]), array([5, 6])]

**np.unique()**
- Finds unique elements of an array.

In [39]:
np.unique([1, 2, 2, 3, 3])  # [1, 2, 3]

array([1, 2, 3])